security:
  oauth2:
    client:
      clientId: 2187759131322524
      clientSecret: f8c44118533c0a5eca7f7b8c3d97962a
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me