server:
  port: 9999

# client is defined in Authorization Server application.yml
spring:
  security:
    oauth2:
      client:
        client-id: 2643da45-a9aa-4753-991b-82cd382250ec
        client-secret: 10d83a61-4c91-470d-95b5-58e47ad2a8f3
        access-token-uri: http://localhost:8080/oauth/token
        user-authorization-uri: http://localhost:8080/oauth/authorize
      resource:
        user-info-uri: http://localhost:8080/user
